# Generated by Django 4.0.6 on 2022-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeplanet', models.FloatField(blank=True, db_column='HomePlanet', null=True)),
                ('cryosleep', models.FloatField(blank=True, db_column='CryoSleep', null=True)),
                ('destination', models.FloatField(blank=True, db_column='Destination', null=True)),
                ('age', models.FloatField(blank=True, db_column='Age', null=True)),
                ('vip', models.FloatField(blank=True, db_column='VIP', null=True)),
                ('roomservice', models.FloatField(blank=True, db_column='RoomService', null=True)),
                ('foodcourt', models.FloatField(blank=True, db_column='FoodCourt', null=True)),
                ('shoppingmall', models.FloatField(blank=True, db_column='ShoppingMall', null=True)),
                ('spa', models.FloatField(blank=True, db_column='Spa', null=True)),
                ('vrdeck', models.FloatField(blank=True, db_column='VRDeck', null=True)),
                ('transported', models.IntegerField(blank=True, db_column='Transported', null=True)),
                ('cabin_deck', models.FloatField(blank=True, db_column='Cabin_Deck', null=True)),
                ('cabin_num', models.IntegerField(blank=True, db_column='Cabin_Num', null=True)),
                ('cabin_side', models.FloatField(blank=True, db_column='Cabin_Side', null=True)),
                ('passengerid', models.CharField(db_column='PassengerId', max_length=15)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeplanet', models.FloatField(blank=True, db_column='HomePlanet', null=True)),
                ('cryosleep', models.FloatField(blank=True, db_column='CryoSleep', null=True)),
                ('destination', models.FloatField(blank=True, db_column='Destination', null=True)),
                ('age', models.FloatField(blank=True, db_column='Age', null=True)),
                ('vip', models.FloatField(blank=True, db_column='VIP', null=True)),
                ('roomservice', models.FloatField(blank=True, db_column='RoomService', null=True)),
                ('foodcourt', models.FloatField(blank=True, db_column='FoodCourt', null=True)),
                ('shoppingmall', models.FloatField(blank=True, db_column='ShoppingMall', null=True)),
                ('spa', models.FloatField(blank=True, db_column='Spa', null=True)),
                ('vrdeck', models.FloatField(blank=True, db_column='VRDeck', null=True)),
                ('transported', models.IntegerField(blank=True, db_column='Transported', null=True)),
                ('cabin_deck', models.FloatField(blank=True, db_column='Cabin_Deck', null=True)),
                ('cabin_num', models.IntegerField(blank=True, db_column='Cabin_Num', null=True)),
                ('cabin_side', models.FloatField(blank=True, db_column='Cabin_Side', null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
